### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by ThePlenkov** [Yobuligo/TypeScriptToABAP#1]
Hi! Nice idea - I see we started almost same time working on a similar topic. 

I see you decided to go really strict way - that may require a lot of work =)

I went instead too simple generic way:
https://github.com/ThePlenkov/abapify/tree/main/packages/abapgen

And using native typescript to introduce limitations ( but only as a concept yet )
https://github.com/ThePlenkov/abapify/blob/8538ffd8ab08f619bfd962da60976005f6fe0590/packages/abapgen-types/src/lib/abapgen-types.spec.ts#L33

It was done to write openapi-to-abap generator:
https://github.com/ThePlenkov/abapify/blob/main/packages/abapgen-openapi/src/lib/abapgen-openapi.spec.ts

and is supposed to be called from CLI
```
abapgen --from=https://petstore3.swagger.io/api/v3/openapi.json --classname=zcl_petstore_client
```

There is already existing solution from Lars Hvam, which is really great - but it's written in ABAP - and to run it locally it may be challenging ( but possible )

What's your intention to create codegen? 

Thanks!
```

**Comment by Yobuligo** [comment]
Hello,

thanks so much for getting in contact with me and sharing your thoughts with me.
I really like your approach and the design of your api. It looks very simple to me and with the readMe already very professional. One of my next step would be to provide a module. Not even know how to do that :P.
And I didn't know there is already a pretty printer lib for abap.
Do you work a lot with Git and TypeScript? Probably you are much deeper into working with it, reusing existing projects etc.

My goal at the end is to write an app with TypeScript and convert it to ABAP to run it within the ABAP runtime environment.
Mainly I am working as an ABAP developer. At the moment we (my company and my team) started a project to provide an ABAP API, to write React apps in ABAP. Even so there are better solutions, it was decided by the management to follow that path. Anyway. But so I got in contact with TypeScript and started it from scratch. My idea was to play around by writing instead a small API to convert TypeScript code to ABAP to use it later for writing small reports and use the advantages like generics, functional methods and the nice short syntax. Well, mainly a private project for learning reasons :P. Probably I will show it to my team it case they want to reuse it.

Best regards

**Comment by ThePlenkov** [comment]
React on ABAP? Wow! Do you mean SSR?

**Comment by Yobuligo** [comment]
Yes, exactly. Sounds like you already have some experience with it :P?
